FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY storage_node/ ./storage_node/

EXPOSE 8001

CMD ["uvicorn", "storage_node.node:app", "--host", "0.0.0.0", "--port", "8001"]
